"""
This script can be used to delete the extra lines from the loss_*.csv file generated by the train_equivariant_manual.py
script
"""
from tqdm import tqdm


new_file = open("NAS Hyperparameters/loss10000_modified.csv", 'w')  # new_file name which does not have extra spaces
with open("NAS Hyperparameters/loss10000.csv", 'r') as file:  # file with extra spaces
    lines = file.read()
    lines = lines.split(sep='\n')
    for line in tqdm(lines):
        if len(line) > 1:
            new_file.writelines(line + '\n')
new_file.close()
print("Done")
